### ISSUE TITLE
pt_email is listed twice in host.example

### ISSUE THREAD

**Issue by frob** [blastehh/pterodactyl_ansible#3]
I noticed the key for `pt_email` is listed twice.

```toml
[pteropanel:vars]
pt_email=<YOUR EMAIL> #CHANGE ME - Your Email Address
pt_email=<YOUR PANEL EMAIL ADDRESS> #CHANGE ME - Panel Send From Email Address
pt_email_from=Pterodactyl Panel #CHANGE ME - Panel Send From Email Name
```
